- name: Remove GCE instance
  hosts: localhost
  gather_facts: false
  vars_files:
    - secrets/vars.yml

  tasks:
    - name: "Remove instance"
      gcp_compute_instance:
        name: "{{ instance_name }}"
        zone: "{{ zone }}"
        project: "{{ project_id }}"
        auth_kind: serviceaccount
        service_account_file: "{{ service_account_file }}"
        state: absent
      register: result

    - name: "Print instance info"
      debug:
        var: result

    - name: Remove host from inventory file
      lineinfile:
        path: "{{ inventory_file }}"
        state: absent
        regexp: "^{{ instance_name }}"